### MYSQLDB

In [6]:

con.query("SELECT VERSION()");
result = con.use_result();
result;


In [9]:
result
    

<_mysql.result object at 9e92cfc>

In [10]:
result.fetch_row()[0]

('5.5.32-0ubuntu0.12.10.1',)

In [11]:
con.close()

In [3]:
import MySQLdb as m
m.connect??

In [20]:
con.rows

()

In [1]:
from bottle import route, request

In [ ]:
import MySQLdb as mdb
ip="tessarinseve.mysql.pythonanywhere-services.com"
con = mdb.connect(ip,"tessarinseve","reverse3","tessarinseve$default")

In [8]:
for con.row in con.rows:
    print(con.row)

{'wordtype': 'n.', 'definition': 'The spoken sign of a conception or an idea; an articulate or\n   vocal sound, or a combination of articulate and vocal sounds, uttered\n   by the human voice, and by custom expressing an idea or ideas; a single\n   component part of human speech or language; a constituent part of a\n   sentence; a term; a vocable.', 'word': 'Word'}
{'wordtype': 'n.', 'definition': 'Hence, the written or printed character, or combination of\n   characters, expressing such a term; as, the words on a page.', 'word': 'Word'}
{'wordtype': 'n.', 'definition': 'Talk; discourse; speech; language.', 'word': 'Word'}
{'wordtype': 'n.', 'definition': 'Account; tidings; message; communication; information; --\n   used only in the singular.', 'word': 'Word'}
{'wordtype': 'n.', 'definition': 'Signal; order; command; direction.', 'word': 'Word'}
{'wordtype': 'n.', 'definition': 'Language considered as implying the faith or authority of the\n   person who utters it; statement; affirmat

In [122]:
con.close()


In [4]:
con = mdb.connect(ip, 'OpenBase', '', 'EnglishDict')

In [10]:
con.cur = con.cursor(mdb.cursors.DictCursor);
sqlstr="SELECT * FROM entries where word like \'"+"word"+"%\'"
con.cur.execute(sqlstr);
con.rows =con.cur.fetchall();

con.rows

({'definition': 'The spoken sign of a conception or an idea; an articulate or\n   vocal sound, or a combination of articulate and vocal sounds, uttered\n   by the human voice, and by custom expressing an idea or ideas; a single\n   component part of human speech or language; a constituent part of a\n   sentence; a term; a vocable.',
  'word': 'Word',
  'wordtype': 'n.'},
 {'definition': 'Hence, the written or printed character, or combination of\n   characters, expressing such a term; as, the words on a page.',
  'word': 'Word',
  'wordtype': 'n.'},
 {'definition': 'Talk; discourse; speech; language.',
  'word': 'Word',
  'wordtype': 'n.'},
 {'definition': 'Account; tidings; message; communication; information; --\n   used only in the singular.',
  'word': 'Word',
  'wordtype': 'n.'},
 {'definition': 'Signal; order; command; direction.',
  'word': 'Word',
  'wordtype': 'n.'},
 {'definition': 'Language considered as implying the faith or authority of the\n   person who utters it; statem

In [19]:
for con.row in con.rows:
    print(con.row["word"]+"("+con.row["wordtype"]+"): "+con.row["definition"])

Word(n.): The spoken sign of a conception or an idea; an articulate or
   vocal sound, or a combination of articulate and vocal sounds, uttered
   by the human voice, and by custom expressing an idea or ideas; a single
   component part of human speech or language; a constituent part of a
   sentence; a term; a vocable.
Word(n.): Hence, the written or printed character, or combination of
   characters, expressing such a term; as, the words on a page.
Word(n.): Talk; discourse; speech; language.
Word(n.): Account; tidings; message; communication; information; --
   used only in the singular.
Word(n.): Signal; order; command; direction.
Word(n.): Language considered as implying the faith or authority of the
   person who utters it; statement; affirmation; declaration; promise.
Word(n.): Verbal contention; dispute.
Word(n.): A brief remark or observation; an expression; a phrase,
   clause, or short sentence.
Word(v. i.): To use words, as in discussion; to argue; to dispute.
Worded(imp. &

-----------------------------------

### SQLALCHEMY

In [3]:
import sqlalchemy

In [4]:
sqlalchemy.__version__

'0.9.8'

In [13]:
from sqlalchemy import create_engine

In [14]:
engine=create_engine('sqlite:///:memory:',echo=True)

In [15]:
# default
engineMysql = create_engine('mysql://OpenBase:@'+ip+'/OpenBase')

# mysql-python
#engine = create_engine('mysql+mysqldb://scott:tiger@localhost/foo')

# MySQL-connector-python
#engine = create_engine('mysql+mysqlconnector://scott:tiger@localhost/foo')

# OurSQL
#engine = create_engine('mysql+oursql://scott:tiger@localhost/foo')

In [16]:
engineMysql

Engine(mysql://OpenBase:***@192.168.56.10/OpenBase)

###### dialect+driver://username:password@host:port/database

In [17]:
result=engineMysql.execute('SELECT * from Logs')

In [22]:
result.keys()


[u'Date', u'Progressive', u'User', u'DidWhat']

In [23]:
for r in result.fetchall():
    print(r)

(datetime.date(2013, 3, 12), 1L, 'Seve', 'Test DB')
(None, 2L, 'Boh', 'Python DB')


--------------------------

### Ipython-Sql

In [1]:
%load_ext sql

In [6]:
ip

'192.168.56.10'

In [2]:
%sql  mysql://OpenBase:@192.168.56.10/OpenBase

u'Connected: OpenBase@OpenBase'

In [9]:
%sql select * from Logs

2 rows affected.


[(datetime.date(2013, 3, 12), 1L, 'Seve', 'Test DB'),
 (None, 2L, 'Boh', 'Python DB')]

In [10]:
result=_

In [12]:
result.csv

<bound method ResultSet.csv of [(datetime.date(2013, 3, 12), 1L, 'Seve', 'Test DB'), (None, 2L, 'Boh', 'Python DB')]>

http://dev.mysql.com/doc/connector-python/en/connector-python-installation-binary.html

In [2]:
%sql  mysql://OpenBase:@192.168.56.10/EnglishDict

u'Connected: OpenBase@EnglishDict'

In [5]:
%sql select * from entries LIMIT 0 , 30

30 rows affected.


[('A', '', 'The first letter of the English and of many other alphabets. The\n   capital A of the alphabets of Middle and Western Europe, as also the\n   small letter (a), besides the forms in Italic, black letter, etc., are\n   all descended from the old Latin A, which was borrowed from the Greek\n   Alpha, of the same form; and this was made from the first letter (/) of\n   the Phoenician alphabet, the equivalent of the Hebrew Aleph, and itself\n   from the Egyptian origin. The Aleph was a consonant letter, with a\n   guttural breath sound that was not an element of Greek articulation;\n   and the Greeks took it to represent their vowel Alpha with the a sound,\n   the Phoenician alphabet having no vowel symbols.'),
 ('A', '', 'The name of the sixth tone in the model major scale (that in C),\n   or the first tone of the minor scale, which is named after it the scale\n   in A minor. The second string of the violin is tuned to the A in the\n   treble staff. -- A sharp (A/) is the name of a musical tone\n   intermediate between A and B. -- A flat (A/) is the name of a tone\n   intermediate between A and G.'),
 ('A', '', 'An adjective, commonly called the indefinite article, and\n   signifying one or any, but less emphatically.'),
 ('A', '', 'In each; to or for each; as, "twenty leagues a day", "a hundred\n   pounds a year", "a dollar a yard", etc.'),
 ('A', 'prep.', 'In; on; at; by.'),
 ('A', 'prep.', 'In process of; in the act of; into; to; -- used with verbal\n   substantives in -ing which begin with a consonant. This is a shortened\n   form of the preposition an (which was used before the vowel sound); as\n   in a hunting, a building, a begging.'),
 ('A', '', 'Of.'),
 ('A', '', 'A barbarous corruption of have, of he, and sometimes of it and of\n   they.'),
 ('A', '', 'An expletive, void of sense, to fill up the meter'),
 ('A-', '', 'A, as a prefix to English words, is derived from various sources.\n   (1) It frequently signifies on or in (from an, a forms of AS. on),\n   denoting a state, as in afoot, on foot, abed, amiss, asleep, aground,\n   aloft, away (AS. onweg), and analogically, ablaze, atremble, etc. (2)\n   AS. of off, from, as in adown (AS. ofd/ne off the dun or hill). (3) AS.\n   a- (Goth. us-, ur-, Ger. er-), usually giving an intensive force, and\n   sometimes the sense of away, on, back, as in arise, abide, ago. (4) Old\n   English y- or i- (corrupted from the AS. inseparable particle ge-,\n   cognate with OHG. ga-, gi-, Goth. ga-), which, as a prefix, made no\n   essential addition to the meaning, as in aware. (5) French a (L. ad\n   to), as in abase, achieve. (6) L. a, ab, abs, from, as in avert. (7)\n   Greek insep. prefix / without, or privative, not, as in abyss, atheist;\n   akin to E. un-.'),
 ('A 1', '', "A registry mark given by underwriters (as at Lloyd's) to ships\n   in first-class condition. Inferior grades are indicated by A 2 and A 3."),
 ('Aam', 'n.', 'A Dutch and German measure of liquids, varying in different\n   cities, being at Amsterdam about 41 wine gallons, at Antwerp 36 1/2, at\n   Hamburg 38 1/4.'),
 ('Aard-vark', 'n.', 'An edentate mammal, of the genus Orycteropus, somewhat\n   resembling a pig, common in some parts of Southern Africa. It burrows\n   in the ground, and feeds entirely on ants, which it catches with its\n   long, slimy tongue.'),
 ('Aard-wolf', 'n.', 'A carnivorous quadruped (Proteles Lalandii), of South\n   Africa, resembling the fox and hyena. See Proteles.'),
 ('Aaronic', 'a.', 'Alt. of Aaronical'),
 ('Aaronical', 'a.', 'Pertaining to Aaron, the first high priest of the Jews.'),
 ("Aaron's rod", '', 'A rod with one serpent twined around it, thus differing\n   from the caduceus of Mercury, which has two.'),
 ("Aaron's rod", '', 'A plant with a tall flowering stem; esp. the great\n   mullein, or hag-taper, and the golden-rod.'),
 ('Ab-', '', 'A prefix in many words of Latin origin. It signifies from, away\n   , separating, or departure, as in abduct, abstract, abscond. S

-------------------

In [1]:
import matplotlib
matplotlib.use('Agg')

from matplotlib import pyplot
import numpy

from flask import Flask, send_file
from cStringIO import StringIO

In [8]:
import MySQLdb as mdb
ip='192.168.56.10'
database="CurveFittingEngine"
table="FitData"
con = mdb.connect(ip, 'OpenBase', '', database)
con.cur = con.cursor(mdb.cursors.DictCursor);
con.cur.execute("SELECT * FROM "+table)
con.rows =con.cur.fetchall();

In [9]:
con.rows

()

In [42]:
x=arange(0,100,1)

In [18]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [43]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
y=2*x

In [45]:
y

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [46]:
type(x)

numpy.ndarray

In [47]:
import cPickle

In [48]:
xo=cPickle.dumps(x)

In [49]:
yo=cPickle.dumps(y)

In [67]:
import requests as r
url="http://tessarinseve.pythonanywhere.com/curvefittingengine"
se={"x":xo,"y":yo}
factor= r.post(url, se)
    

In [81]:
import IPython.display as IPD
result=str(factor.text)
d=eval(result)

{'report': "S'[[Model]]\\n    Model(linear)\\n[[Fit Statistics]]\\n    # function evals   = 6\\n    # data points      = 100\\n    # variables        = 2\\n    chi-square         = 0.000\\n    reduced chi-square = 0.000\\n[[Variables]]\\n    slope:       2          +/- 7.47e-27 (0.00%) (init= 2)\\n    intercept:   4.2376e-23 +/- 4.28e-24 (10.10%) (init=-1.136868e-14)\\n[[Correlations]] (unreported correlations are <  0.100)\\n'\np1\n.",
 'x': 'cnumpy.core.multiarray\n_reconstruct\np1\n(cnumpy\nndarray\np2\n(I0\ntS\'b\'\ntRp3\n(I1\n(I100\ntcnumpy\ndtype\np4\n(S\'i4\'\nI0\nI1\ntRp5\n(I3\nS\'<\'\nNNNI-1\nI-1\nI0\ntbI00\nS\'\\x00\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x02\\x00\\x00\\x00\\x03\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x05\\x00\\x00\\x00\\x06\\x00\\x00\\x00\\x07\\x00\\x00\\x00\\x08\\x00\\x00\\x00\\t\\x00\\x00\\x00\\n\\x00\\x00\\x00\\x0b\\x00\\x00\\x00\\x0c\\x00\\x00\\x00\\r\\x00\\x00\\x00\\x0e\\x00\\x00\\x00\\x0f\\x00\\x00\\x00\\x10\\x00\\x00\\x00\\x11\\x00\\x00\\x00\\x12\\x00\\x00\\x

In [36]:
cPickle.loads(xo)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
grant select on database_name.* to 'read-only_user_name'@'%' identified by 'password';

In [56]:
dictofpickle={}


In [57]:
dictofpickle["x"]=xo

In [58]:
dictofpickle["y"]=yo

In [64]:
cPickle.loads(dictofpickle["x"])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])